### ISSUE TITLE
with_deleted not working properly

### ISSUE THREAD

**Issue by joelmichael** [grosser/soft_deletion#24]
Just cases like `User.with_deleted { User.first }` no longer work. It complains that core.rb line 23 is expecting an ActiveRecord::Relation. We've had to roll back to 0.7.0 for now.

**Comment by grosser** [comment]
can you paste a backtrace ?

... do you know what needs to change to fix that ?

**Comment by joelmichael** [comment]
Here's a backtrace

```
irb(main):005:0> User.with_deleted { User.first }
ArgumentError: User(old_id: integer, email: string, encrypted_password: string, reset_password_token: string, reset_password_sent_at: datetime, remember_created_at: datetime, sign_in_count: integer, current_sign_in_at: datetime, last_sign_in_at: datetime, current_sign_in_ip: string, last_sign_in_ip: string, authentication_token: string, created_at: datetime, updated_at: datetime, type: string, name: string, data: text, id: integer, approved: boolean, slug: string, tos_accepted: boolean, utm_source: string, utm_campaign: string, utm_medium: string, utm_term: string, utm_content: string, utm_location: string, deleted_at: datetime, company_id: integer, profile_id: integer, phone: string, approved_by_id: integer, funnel_state: string, approved_at: datetime, rejected_by_id: integer, rejected_at: datetime, survey_data: hstore, native_client_token: string, marketo_id: integer, time_zone: string, locale_id: integer, signup_email: string, first_browser_uuid: string, salesforce_id: string, dont_send_sms_messages: boolean, curation_status: string, optimizely_end_user_id: string, optimizely_buckets: text, location_id: integer, confirmation_token: string, confirmed_at: datetime, confirmation_sent_at: datetime, last_impression_at: datetime, approved_level: string, optimizely_segments: text, show_auth_popup: boolean, optimizely_created_at: datetime, preferences: jsonb, default_params: jsonb, first_ios_app_sign_in: datetime, address: string, place_id: integer, market_id: integer, web_notifications_state: string) is not an ActiveRecord::Relation
	from /Users/joel/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/relation/spawn_methods.rb:48:in `merge!'
	from /Users/joel/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/relation/spawn_methods.rb:34:in `merge'
	from /Users/joel/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/scoping/default.rb:105:in `block (2 levels) in build_default_scope'
	from /Users/joel/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/scoping/default.rb:104:in `each'
	from /Users/joel/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/scoping/default.rb:104:in `inject'
	from /Users/joel/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/scoping/default.rb:104:in `block in build_default_scope'
	from /Users/joel/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/scoping/default.rb:127:in `evaluate_default_scope'
	from /Users/joel/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/scoping/default.rb:103:in `build_default_scope'
	from /Users/joel/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/scoping/named.rb:33:in `default_scoped'
	from /Users/joel/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/scoping/named.rb:28:in `all'
	from /Users/joel/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/querying.rb:3:in `first'
	from (irb):5:in `block in irb_binding'
	from /Users/joel/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/soft_deletion-0.8.0/lib/soft_deletion/core.rb:23:in `with_deleted'
	from (irb):5
	from /Users/joel/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/console.rb:110:in `start'
	from /Users/joel/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/console.rb:9:in `start'
... 2 levels...
	from /Users/joel/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/commands.rb:17:in `<top (required)>'
	from /Users/joel/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bootscale-0.5.2/lib/bootscale/core_ext.rb:4:in `require'
	from /Users/joel/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bootscale-0.5.2/lib/bootscale/core_ext.rb:4:in `require'
	from /Users/joel/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
	from /Users/joel/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/skylight-0.10.6/lib/skylight/probes.rb:81:in `require'
	from /Users/joel/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/joel/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/joel/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
	from /Users/joel/Code/hired/bin/rails:9:in `<top (required)>'
	from /Users/joel/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
	from /Users/joel/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `block in load'
	from /Users/joel/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/joel/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
	from /Users/joel/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/joel/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'

```

I'm not sure what needs to change, it's possible it's something weird on our end but idk, it works in 0.7.0

**Comment by grosser** [comment]
might be the `where(nil)` ... in setup.rb ... can you try changing that to something else like `where('1=2')` ?

**Comment by grosser** [comment]
`where('1=1')`

**Comment by joelmichael** [comment]
That appears to fix the problem, although it's not ideal...

**Comment by grosser** [comment]
can you reproduce a failing test ?
it's tested against 4.2.71 and works fine ... so maybe some combination of your apps gems/hacks is breaking that ?

**Comment by joelmichael** [comment]
This problem is entirely on our end. I'm sorry to waste your time. We have a goofy custom library that was breaking it.

**Comment by grosser** [comment]
Glad to know it's not some goofy bug :D
